import os
import random
from datetime import datetime

# ===== CONFIG =====
SITE_NAME = "HubGaming AI"
AUTHOR = "HubGaming Team"

TITLES = [
    "Pro Playbook: Reinforcement Learning for Esports Strategy in 2025",
    "AI Coaching: How Pro Teams Train Smarter in High-Tempo Esports",
    "From VOD to Live Inference: AI Telemetry Changing Esports",
    "Meta Prediction AI: How Teams Counter Strategies Before They Happen",
    "AI Esports Scrim Labs: Simulated Training for Pro Teams",
]

PARAGRAPHS = [
    "AI-driven environments and adaptive economies make each session unique. The fusion of AI + blockchain is building valuable virtual economies with verifiable ownership.",
    "Elite teams treat operations like products: they ship strategy, measure impact, and roll back safely. High-stakes esports reward good process over raw talent.",
    "Telemetry-informed coaching replaces guesswork with testable interventions. Role clarity and automated reviews reduce micro mistakes in long series.",
    "Reinforcement learning agents help teams optimize tempo, rotations, vision control, and engagement precision.",
    "Smart anti-cheat AI models detect unusual aim patterns, decision anomalies, and cross-input inconsistencies in milliseconds.",
]

KEYPOINTS = [
    "AI-driven strategy reduces tilt and improves decision-making under pressure.",
    "Telemetry coaching eliminates guesswork and speeds up pro development.",
    "Blockchain-verified assets increase player ownership and fan engagement.",
    "Adaptive meta-training improves win consistency across patches.",
]

BACKLINKS = [
    ("botplay.io", "https://botplay.io"),
    ("botweb3ai.com", "https://botweb3ai.com"),
    ("metaversebot.io", "https://metaversebot.io"),
    ("hubgaming.io", "https://hubgaming.io"),
    ("bottradingai.com", "https://bottradingai.com"),
]

# ===== GENERATE POST =====

def generate_post():
    today = datetime.utcnow().strftime("%Y-%m-%d")
    title = random.choice(TITLES)
    safe_title = title.lower().replace(" ", "-").replace(":", "").replace("'", "")
    filename = f"_posts/{today}-{safe_title}.md"

    # chọn 1 intro + 1 body không trùng
    intro, body = random.sample(PARAGRAPHS, k=2)

    # random ảnh đẹp chất lượng cao
    image_url = f"https://images.pexels.com/photos/{random.randint(1000000,9999999)}/pexels-photo.jpeg?auto=compress&cs=tinysrgb&w=1200"

    # YAML + CONTENT BUILD
    content = f"""---
layout: post
title: "{title}"
date: {today}
author: "{AUTHOR}"
description: "AI + Esports insights auto-generated for {SITE_NAME}"
image: "{image_url}"
---

_This article was auto-generated by {SITE_NAME} (Authority SEO)._


![{title}]({image_url})

{intro}

{body}

### Key Insights
"""

    for kp in KEYPOINTS:
        content += f"- {kp}\n"

    # BACKLINK SECTION – ngắn gọn – không spam
    content += "\n### Friendly Network\n"
    for name, link in random.sample(BACKLINKS, k=3):
        content += f"- [{name}]({link})\n"

    # CTA
    content += f"""

**Conclusion:** AI-powered esports strategy will redefine competitive gaming — and {SITE_NAME} is tracking it daily.

"""

    # Save file
    os.makedirs("_posts", exist_ok=True)
    with open(filename, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"✅ New post generated: {filename}")


if __name__ == "__main__":
    generate_post()
